# Generated by Django 2.2.10 on 2021-01-10 13:43

from django.db import migrations, models
import sample.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HandwritingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=sample.models.handwriting_img_path)),
            ],
        ),
    ]
